project:
  type: website
  output-dir: docs

website:
  title: "Gurpreet Johl"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/gjohl
      - icon: twitter
        href: https://twitter.com/gurpreetjohl
format:
  html:
    theme: journal
    css: styles.css



